/* DSblock model generated by Dymola from Modelica model Simple_car_dymola.Experiment.Experiment_1
 Dymola Version 2017 (64-bit), 2016-06-23 translated this at Thu Aug 30 22:30:11 2018

   */

#include <matrixop.h>
/* Declaration of C-structs */
/* Prototypes for functions used in model */
/* Codes used in model */
/* DSblock C-code: */

#define NX_    6
#define NX2_   0
#define NU_    0
#define NY_    0
#define NW_    53
#define NP_    22
#define NPS_   0
#define MAXAuxStr_   0
#define MAXAuxStrLen_   500
#define NHash1_ 616827447
#define NHash2_ 1799586117
#define NHash3_ 0
#define NI_    0
#define NRelF_ 0
#define NRel_  1
#define NTim_  1
#define NSamp_ 0
#define NCons_ 0
#define NA_    27
#define SizePre_ 0
#define SizeEq_ 3
#define SizeDelay_ 0
#define QNLmax_ 0
#define MAXAux 0
#define NrDymolaTimers_ 0
#define NWhen_ 0
#define NCheckIf_ 0
#define NGlobalHelp_ 30
#define NGlobalHelpI_ 0
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif
#include <moutil.c>
PreNonAliasDef(0)
PreNonAliasDef(1)
PreNonAliasDef(2)
PreNonAliasDef(3)
PreNonAliasDef(4)
PreNonAliasDef(5)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="Simple_car_dymola.Experiment.Experiment_1";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=0;
#define QJacobianCGDef_ 1
DYMOLA_STATIC int QJacobianCG_[10]={3 , 3 , 1 , 5 , 6 , 2 , 2 , 3 , 1 , 4};
DYMOLA_STATIC int QJacobianGC_[19]={
1 , 0 , 1 , 1 , 1 , 1 , 3 , 3 , 3 , 3 , 2 , 2 , 4 , 0 , 4 , 4 , 4 , 4 , 0};
DYMOLA_STATIC double QJacobianCD_[7]={0  , 44 , 50 , 60 , 63 , 88 , 99};
#include <dsblock1.c>

/* Define variable names. */

#define Sections_

TranslatedEquations

InitialSection
#if defined(DynSimStruct) || defined(BUILDFMU)
DYNX(W_,0) = 9.80665;
DYNX(W_,15) = 9.80665;
DYNX(W_,16) = 3.141592653589793;
DYNX(W_,31) = 9.80665;
DYNX(W_,32) = 3.141592653589793;
DYNX(W_,51) = 3.141592653589793;
DYNX(W_,22) = 32;
DYNX(W_,38) = 0;
DYNX(W_,36) = 32;
DYNX(W_,45) = 0;
DYNX(W_,10) = 0.0;
DYNX(W_,11) = 32.0;
DYNX(W_,52) = 1.9198621771937625;
DYNX(W_,12) = 0.0;
#endif
BoundParameterSection
DYNX(W_,1) = divmacro(DYNX(DP_,0)*DYNX(DP_,2),"vehicle.chassis.m*vehicle.chassis.b",
  DYNX(DP_,1)+DYNX(DP_,2),"vehicle.chassis.a+vehicle.chassis.b");
DYNX(W_,2) = divmacro(DYNX(DP_,0)*DYNX(DP_,1),"vehicle.chassis.m*vehicle.chassis.a",
  DYNX(DP_,1)+DYNX(DP_,2),"vehicle.chassis.a+vehicle.chassis.b");
DYNX(W_,3) = divmacro(9.80665*DYNX(DP_,0)*DYNX(DP_,2),"9.80665*(vehicle.chassis.m*vehicle.chassis.b)",
  DYNX(DP_,1)+DYNX(DP_,2),"vehicle.chassis.a+vehicle.chassis.b");
DYNX(W_,4) = divmacro(9.80665*DYNX(DP_,0)*DYNX(DP_,1),"9.80665*(vehicle.chassis.m*vehicle.chassis.a)",
  DYNX(DP_,1)+DYNX(DP_,2),"vehicle.chassis.a+vehicle.chassis.b");
DYNX(W_,17) = DYNX(DP_,7);
DYNX(W_,18) = DYNX(W_,1);
DYNX(W_,33) = DYNX(DP_,7);
DYNX(W_,34) = DYNX(W_,2);
InitialSection
#if defined(DynSimStruct) || defined(BUILDFMU)
DYNX(W_,9) = 0.0;
DYNX(W_,13) = 0;
DYNX(W_,19) = 0.0;
DYNX(W_,35) = 0.0;
DYNX(W_,48) = 0;
#endif
InitialSection
InitialStartSection
InitialStartSection2
DYNX(X_,3) = DYNX(DP_,7);
InitialSection
DefaultSection
InitializeData(0)
InitialSection
InitialSection2
DYNX(X_,3) = DYNX(DP_,7);
InitialSection2
Init_=false;InitializeData(2);Init_=true;
EndInitialSection

OutputSection

DynamicsSection
DYNX(W_,44) = IF LessTime(25, 0) THEN 0 ELSE 1.5;
DYNX(W_,50) = divmacro(DYNX(W_,44),"vehicle.swa",DYNX(DP_,4),"vehicle.chassis.i_s");
DYNX(W_,19) = DYNX(X_,0)+DYNX(X_,2)*DYNX(DP_,1);
DYNX(DYNhelp,0) = cos(DYNX(W_,50));
DYNX(DYNhelp,1) = sin(DYNX(W_,50));
DYNX(W_,20) = DYNX(X_,3)*DYNX(DYNhelp,0)+DYNX(W_,19)*DYNX(DYNhelp,1);
DYNX(DYNhelp,2) = 32.0*DYNX(DP_,12);
if (NewParameters_) {
DYNX(DYNhelp,3) = fabs(DYNX(DYNhelp,2));
}
if (NewParameters_) {
DYNX(DYNhelp,4) = RealBmax(DYNX(DYNhelp,3), 0.01);
}
DYNX(DYNhelp,5) = divmacro(1.0,"1.0",DYNX(DYNhelp,4),"max(abs(32.0*vehicle.wheel1.rw), 0.01)");
DYNX(W_,29) =  -DYNX(DYNhelp,5)*(DYNX(W_,20)-DYNX(DYNhelp,2));
DYNX(W_,21) = DYNX(W_,19)*DYNX(DYNhelp,0)-DYNX(X_,3)*DYNX(DYNhelp,1);
DYNX(DYNhelp,6) = divmacro(1.0,"1.0",DYNX(DYNhelp,4),"max(abs(32.0*vehicle.wheel1.rw), 0.01)");
DYNX(W_,30) = DYNX(DYNhelp,6)*DYNX(W_,21);
DYNX(W_,27) = sqrtGuarded(sqr(DYNX(W_,29))+sqr(DYNX(W_,30)),"vehicle.wheel1.sx^2+vehicle.wheel1.sy^2");
DYNX(DYNhelp,7) = atan(0.6366197723675814*DYNX(DP_,13)*DYNX(W_,27));
DYNX(W_,28) = 0.6366197723675814*DYNX(DYNhelp,7);
DYNX(W_,23) = DYNX(DP_,14)*DYNX(W_,3)*DYNX(W_,28);
DYNX(DYNhelp,8) = 32.0*DYNX(DP_,12)-DYNX(W_,20);
DYNX(DYNhelp,9) = sqrtGuarded(sqr(DYNX(DYNhelp,8))+sqr(DYNX(W_,21)),
  "(32.0*vehicle.wheel1.rw-vehicle.wheel1.vx)^2+vehicle.wheel1.vy^2");
DYNX(DYNhelp,10) = RealBmax(DYNX(DYNhelp,9), 0.01);
DYNX(DYNhelp,11) = divmacro(1.0,"1.0",DYNX(DYNhelp,10),"max(sqrt((32.0*vehicle.wheel1.rw-vehicle.wheel1.vx)^2+vehicle.wheel1.vy^2), 0.01)");
DYNX(W_,24) = DYNX(DYNhelp,11)*DYNX(DYNhelp,8)*DYNX(W_,23);
DYNX(DYNhelp,12) = divmacro(1.0,"1.0",DYNX(DYNhelp,10),"max(sqrt((32.0*vehicle.wheel1.rw-vehicle.wheel1.vx)^2+vehicle.wheel1.vy^2), 0.01)");
DYNX(W_,25) =  -DYNX(DYNhelp,12)*DYNX(W_,21)*DYNX(W_,23);
DYNX(W_,14) = DYNX(DYNhelp,1)*DYNX(W_,24)+DYNX(DYNhelp,0)*DYNX(W_,25);
DYNX(W_,35) = DYNX(X_,0)-DYNX(X_,2)*DYNX(DP_,2);
DYNX(DYNhelp,13) = 32.0*DYNX(DP_,17);
if (NewParameters_) {
DYNX(DYNhelp,14) = fabs(DYNX(DYNhelp,13));
}
if (NewParameters_) {
DYNX(DYNhelp,15) = RealBmax(DYNX(DYNhelp,14), 0.01);
}
DYNX(DYNhelp,16) = divmacro(1.0,"1.0",DYNX(DYNhelp,15),"max(abs(32.0*vehicle.wheel2.rw), 0.01)");
DYNX(W_,42) =  -DYNX(DYNhelp,16)*(DYNX(X_,3)-DYNX(DYNhelp,13));
DYNX(DYNhelp,17) = divmacro(1.0,"1.0",DYNX(DYNhelp,15),"max(abs(32.0*vehicle.wheel2.rw), 0.01)");
DYNX(W_,43) = DYNX(DYNhelp,17)*DYNX(W_,35);
DYNX(W_,40) = sqrtGuarded(sqr(DYNX(W_,42))+sqr(DYNX(W_,43)),"vehicle.wheel2.sx^2+vehicle.wheel2.sy^2");
DYNX(DYNhelp,18) = atan(0.6366197723675814*DYNX(DP_,18)*DYNX(W_,40));
DYNX(W_,41) = 0.6366197723675814*DYNX(DYNhelp,18);
DYNX(W_,37) = DYNX(DP_,19)*DYNX(W_,4)*DYNX(W_,41);
DYNX(DYNhelp,19) = sqrtGuarded(sqr(32.0*DYNX(DP_,17)-DYNX(X_,3))+sqr(DYNX(W_,35)),
  "(32.0*vehicle.wheel2.rw-vehicle.chassis.vx)^2+vehicle.wheel2.Vy^2");
DYNX(DYNhelp,20) = RealBmax(DYNX(DYNhelp,19), 0.01);
DYNX(DYNhelp,21) = divmacro(1.0,"1.0",DYNX(DYNhelp,20),"max(sqrt((32.0*vehicle.wheel2.rw-vehicle.chassis.vx)^2+vehicle.wheel2.Vy^2), 0.01)");
DYNX(W_,7) =  -DYNX(DYNhelp,21)*DYNX(W_,35)*DYNX(W_,37);
 /* Linear system of equations to solve. */
DYNX(F_,2) = RememberSimple_(DYNX(F_,2), 0);
SolveScalarLinearParametric(DYNX(DP_,3),"vehicle.chassis.Izz", DYNX(DP_,1)*
  DYNX(W_,14)-DYNX(DP_,2)*DYNX(W_,7),"vehicle.chassis.a*vehicle.chassis.Fyf-vehicle.chassis.b*vehicle.chassis.Fyr",
   DYNX(F_,2),"der(vehicle.chassis.yaw_velocity)");
 /* End of Equation Block */ 

DYNX(W_,6) = DYNX(DYNhelp,0)*DYNX(W_,24)-DYNX(DYNhelp,1)*DYNX(W_,25);
DYNX(DYNhelp,22) = 32.0*DYNX(DP_,17)-DYNX(X_,3);
DYNX(DYNhelp,23) = divmacro(1.0,"1.0",DYNX(DYNhelp,20),"max(sqrt((32.0*vehicle.wheel2.rw-vehicle.chassis.vx)^2+vehicle.wheel2.Vy^2), 0.01)");
DYNX(W_,8) = DYNX(DYNhelp,23)*DYNX(DYNhelp,22)*DYNX(W_,37);
DYNX(W_,9) =  -(IF DYNX(X_,3) > 0 THEN 1 ELSE IF DYNX(X_,3) < 0 THEN -1 ELSE 0)*
  0.5*DYNX(DP_,8)*DYNX(DP_,9)*DYNX(DP_,10)*sqr(DYNX(X_,3));
DYNX(W_,5) = DYNX(W_,6)+DYNX(W_,8)+DYNX(W_,9);
 /* Linear system of equations to solve. */
DYNX(W_,47) = RememberSimple_(DYNX(W_,47), 1);
SolveScalarLinearParametric(DYNX(DP_,0),"vehicle.chassis.m", DYNX(W_,5),
  "vehicle.chassis.Fx", DYNX(W_,47),"vehicle.ax");
 /* End of Equation Block */ 

DYNX(F_,3) = DYNX(W_,47)+DYNX(X_,0)*DYNX(X_,2);
 /* Linear system of equations to solve. */
DYNX(W_,49) = RememberSimple_(DYNX(W_,49), 2);
SolveScalarLinearParametric(DYNX(DP_,0),"vehicle.chassis.m", DYNX(W_,14)+
  DYNX(W_,7),"vehicle.chassis.Fyf+vehicle.chassis.Fyr", DYNX(W_,49),"vehicle.ay");
 /* End of Equation Block */ 

DYNX(F_,0) = DYNX(W_,49)-DYNX(X_,3)*DYNX(X_,2);
DYNX(F_,1) = DYNX(X_,2);
DYNX(DYNhelp,24) = cos(DYNX(X_,1));
DYNX(DYNhelp,25) = sin(DYNX(X_,1));
DYNX(F_,4) = DYNX(X_,3)*DYNX(DYNhelp,24)-DYNX(X_,0)*DYNX(DYNhelp,25);
DYNX(F_,5) = DYNX(X_,0)*DYNX(DYNhelp,24)+DYNX(X_,3)*DYNX(DYNhelp,25);

AcceptedSection1

AcceptedSection2
DYNX(DYNhelp,26) = RealBmax(DYNX(X_,3), 0.01);
DYNX(DYNhelp,27) = divmacro(1.0,"1.0",DYNX(DYNhelp,26),"max(vehicle.chassis.vx, 0.01)");
DYNX(W_,13) = atan(DYNX(DYNhelp,27)*DYNX(X_,0));
DYNX(DYNhelp,28) = RealBmin(1, DYNX(W_,20));
DYNX(W_,26) = 9.80665*DYNX(DP_,16)*DYNX(W_,18)*DYNX(DYNhelp,28);
DYNX(DYNhelp,29) = RealBmin(1, DYNX(X_,3));
DYNX(W_,39) = 9.80665*DYNX(DP_,21)*DYNX(W_,34)*DYNX(DYNhelp,29);
DYNX(W_,46) = RealBmax(DYNX(W_,47), 0);
DYNX(W_,48) = IF Greater(DYNX(W_,47),"vehicle.ax", 0,"0", 0) THEN 0 ELSE 
  DYNX(W_,47);

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareVariable("vehicle.chassis.g", "", 9.80665, 0.0,0.0,0.0,0,513)
DeclareParameter("vehicle.chassis.m", "[kg]", 0, 2194, 0.0,0.0,0.0,0,560)
DeclareParameter("vehicle.chassis.a", "[m]", 1, 1.41, 0.0,0.0,0.0,0,560)
DeclareParameter("vehicle.chassis.b", "[m]", 2, 1.576, 0.0,0.0,0.0,0,560)
DeclareParameter("vehicle.chassis.Izz", "[m2.kg]", 3, 4770, 0.0,0.0,0.0,0,560)
DeclareParameter("vehicle.chassis.i_s", "", 4, 16, 0.0,0.0,0.0,0,560)
DeclareParameter("vehicle.chassis.Iw", "", 5, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("vehicle.chassis.rw", "", 6, 0.3125, 0.0,0.0,0.0,0,560)
DeclareVariable("vehicle.chassis.m_f", "[kg]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("vehicle.chassis.m_r", "[kg]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("vehicle.chassis.Fzf", "[N]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("vehicle.chassis.Fzr", "[N]", 0.0, 0.0,0.0,0.0,0,513)
DeclareParameter("vehicle.chassis.vx0", "[m/s]", 7, 10, 0.0,0.0,0.0,0,560)
DeclareParameter("vehicle.chassis.rho", "air density", 8, 1.225, 0.0,0.0,0.0,0,560)
DeclareParameter("vehicle.chassis.Cd", "Coefficient of drag", 9, 0.3, 0.0,0.0,\
0.0,0,560)
DeclareParameter("vehicle.chassis.ac", "Frontal area", 10, 2.78, 0.0,0.0,0.0,0,560)
DeclareParameter("vehicle.chassis.mu", "Road fricition", 11, 0.9, 0.0,0.0,0.0,0,560)
DeclareState("vehicle.chassis.vy", "Vehicle Lateral Velocity [m/sec] [m/s]", 0, \
0.0, 0.0,0.0,0.0,0,560)
DeclareDerivative("vehicle.chassis.der(vy)", "der(Vehicle Lateral Velocity [m/sec]) [m/s2]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareState("vehicle.chassis.yaw_angle", "[1]", 1, 0, 0.0,0.0,0.0,0,560)
DeclareDerivative("vehicle.chassis.der(yaw_angle)", "[s-1]", 0.0, 0.0,0.0,0.0,0,512)
DeclareState("vehicle.chassis.yaw_velocity", "[s-1]", 2, 0, 0.0,0.0,0.0,0,560)
DeclareDerivative("vehicle.chassis.der(yaw_velocity)", "[s-2]", 0.0, 0.0,0.0,0.0,\
0,512)
DeclareAlias2("vehicle.chassis.yaw_acc", "[s-2]", "vehicle.chassis.der(yaw_velocity)", 1,\
 6, 2, 0)
DeclareAlias2("vehicle.chassis.ay", "[m/s2]", "vehicle.ay", 1, 5, 49, 0)
DeclareVariable("vehicle.chassis.Fx", "[N]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("vehicle.chassis.Fxf", "[N]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("vehicle.chassis.Fyr", "[N]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("vehicle.chassis.Fxr", "[N]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("vehicle.chassis.Fd", "[N]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("vehicle.chassis.Fg", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareAlias2("vehicle.chassis.delta", "[rad]", "vehicle.delta", 1, 5, 50, 0)
DeclareVariable("vehicle.chassis.womega", "", 32.0, 0.0,0.0,0.0,0,513)
DeclareAlias2("vehicle.chassis.swa", "Steering angle [rad] []", "vehicle.swa", 1,\
 5, 44, 0)
DeclareVariable("vehicle.chassis.theta", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("vehicle.chassis.beta", "", 0, 0.0,0.0,0.0,0,512)
DeclareState("vehicle.chassis.vx", "Vehicle longitudinal velocity [m/s]", 3, 0.0,\
 0.0,0.0,0.0,0,544)
DeclareDerivative("vehicle.chassis.der(vx)", "der(Vehicle longitudinal velocity) [m/s2]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareState("vehicle.chassis.x", "", 4, 0, 0.0,0.0,0.0,0,560)
DeclareDerivative("vehicle.chassis.der(x)", "", 0.0, 0.0,0.0,0.0,0,512)
DeclareState("vehicle.chassis.y", "", 5, 0, 0.0,0.0,0.0,0,560)
DeclareDerivative("vehicle.chassis.der(y)", "", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("vehicle.chassis.ax", "[m/s2]", "vehicle.ax", 1, 5, 47, 0)
DeclareVariable("vehicle.chassis.Fyf", "[N]", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("vehicle.chassis.decl", "[m/s2]", "vehicle.decl", 1, 5, 48, 0)
DeclareAlias2("vehicle.chassis.axp", "[m/s2]", "vehicle.ax_sim", 1, 5, 46, 0)
DeclareVariable("vehicle.wheel1.g", "", 9.80665, 0.0,0.0,0.0,0,513)
DeclareVariable("vehicle.wheel1.pi", "", 3.141592653589793, 0.0,0.0,0.0,0,513)
DeclareParameter("vehicle.wheel1.rw", "Radius of wheel [m/rad]", 12, 0.3125, \
0.0,0.0,0.0,0,560)
DeclareParameter("vehicle.wheel1.c", "", 13, 18, 0.0,0.0,0.0,0,560)
DeclareParameter("vehicle.wheel1.mu", "", 14, 0.9, 0.0,0.0,0.0,0,560)
DeclareVariable("vehicle.wheel1.vx0", "[m/s]", 0.0, 0.0,0.0,0.0,0,513)
DeclareParameter("vehicle.wheel1.I_tyre", "", 15, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("vehicle.wheel1.f_r", "Rolling resistance coefficient", 16, \
0.00075, 0.0,0.0,0.0,0,560)
DeclareVariable("vehicle.wheel1.m", "[kg]", 0.0, 0.0,0.0,0.0,0,513)
DeclareAlias2("vehicle.wheel1.Vx", "Chassis long velocity [m/s]", \
"vehicle.chassis.vx", 1, 1, 3, 0)
DeclareVariable("vehicle.wheel1.Vy", "Chassis lat velocity [m/s]", 0.0, 0.0,0.0,\
0.0,0,512)
DeclareVariable("vehicle.wheel1.vx", "wheel lon velocity [m/s]", 0.0, 0.0,0.0,\
0.0,0,512)
DeclareVariable("vehicle.wheel1.vy", "wheel lat velcoity [m/s]", 0.0, 0.0,0.0,\
0.0,0,512)
DeclareVariable("vehicle.wheel1.omega", "wheel angular velocity [rad/s]", 32, \
0.0,0.0,0.0,0,513)
DeclareVariable("vehicle.wheel1.Fxy", "Tire Force combined [N]", 0.0, 0.0,0.0,\
0.0,0,512)
DeclareAlias2("vehicle.wheel1.DeltaWheel", "[rad|deg]", "vehicle.delta", 1, 5, 50,\
 0)
DeclareAlias2("vehicle.wheel1.Fz", "[N]", "vehicle.chassis.Fzf", 1, 5, 3, 0)
DeclareVariable("vehicle.wheel1.Fx", "[N]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("vehicle.wheel1.Fy", "[N]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("vehicle.wheel1.Fr", "[N]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("vehicle.wheel1.sxy", "combined slip", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("vehicle.wheel1.fsxy", "tire coefficient", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("vehicle.wheel1.sx", "longitudinal slip [1]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("vehicle.wheel1.sy", "Lateral slip [1]", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("vehicle.wheel1.F_x", "[N]", "vehicle.chassis.Fxf", 1, 5, 6, 0)
DeclareAlias2("vehicle.wheel1.F_y", "[N]", "vehicle.chassis.Fyf", 1, 5, 14, 0)
DeclareVariable("vehicle.wheel2.g", "", 9.80665, 0.0,0.0,0.0,0,513)
DeclareVariable("vehicle.wheel2.pi", "", 3.141592653589793, 0.0,0.0,0.0,0,513)
DeclareParameter("vehicle.wheel2.rw", "Radius of wheel [m/rad]", 17, 0.3125, \
0.0,0.0,0.0,0,560)
DeclareParameter("vehicle.wheel2.c", "", 18, 18, 0.0,0.0,0.0,0,560)
DeclareParameter("vehicle.wheel2.mu", "", 19, 0.9, 0.0,0.0,0.0,0,560)
DeclareVariable("vehicle.wheel2.vx0", "[m/s]", 0.0, 0.0,0.0,0.0,0,513)
DeclareParameter("vehicle.wheel2.I_tyre", "", 20, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("vehicle.wheel2.f_r", "Rolling resistance coefficient", 21, \
0.00075, 0.0,0.0,0.0,0,560)
DeclareVariable("vehicle.wheel2.m", "[kg]", 0.0, 0.0,0.0,0.0,0,513)
DeclareAlias2("vehicle.wheel2.Vx", "Chassis long velocity [m/s]", \
"vehicle.chassis.vx", 1, 1, 3, 0)
DeclareVariable("vehicle.wheel2.Vy", "Chassis lat velocity [m/s]", 0.0, 0.0,0.0,\
0.0,0,512)
DeclareAlias2("vehicle.wheel2.vx", "wheel lon velocity [m/s]", "vehicle.chassis.vx", 1,\
 1, 3, 0)
DeclareAlias2("vehicle.wheel2.vy", "wheel lat velcoity [m/s]", "vehicle.wheel2.Vy", 1,\
 5, 35, 0)
DeclareVariable("vehicle.wheel2.omega", "wheel angular velocity [rad/s]", 32, \
0.0,0.0,0.0,0,513)
DeclareVariable("vehicle.wheel2.Fxy", "Tire Force combined [N]", 0.0, 0.0,0.0,\
0.0,0,512)
DeclareVariable("vehicle.wheel2.DeltaWheel", "[rad|deg]", 0, 0.0,0.0,0.0,0,513)
DeclareAlias2("vehicle.wheel2.Fz", "[N]", "vehicle.chassis.Fzr", 1, 5, 4, 0)
DeclareAlias2("vehicle.wheel2.Fx", "[N]", "vehicle.chassis.Fxr", 1, 5, 8, 0)
DeclareAlias2("vehicle.wheel2.Fy", "[N]", "vehicle.chassis.Fyr", 1, 5, 7, 0)
DeclareVariable("vehicle.wheel2.Fr", "[N]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("vehicle.wheel2.sxy", "combined slip", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("vehicle.wheel2.fsxy", "tire coefficient", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("vehicle.wheel2.sx", "longitudinal slip [1]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("vehicle.wheel2.sy", "Lateral slip [1]", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("vehicle.wheel2.F_x", "[N]", "vehicle.chassis.Fxr", 1, 5, 8, 0)
DeclareAlias2("vehicle.wheel2.F_y", "[N]", "vehicle.chassis.Fyr", 1, 5, 7, 0)
DeclareVariable("vehicle.swa", "", 0.0, 0.0,0.0,0.0,0,640)
DeclareVariable("vehicle.theta", "", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("vehicle.ax_sim", "[m/s2]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("vehicle.ax", "[m/s2]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("vehicle.decl", "[m/s2]", 0, 0.0,0.0,0.0,0,512)
DeclareAlias2("vehicle.vx", "[m/s]", "vehicle.chassis.vx", 1, 1, 3, 0)
DeclareAlias2("vehicle.yaw_angle", "[1]", "vehicle.chassis.yaw_angle", 1, 1, 1, 0)
DeclareAlias2("vehicle.x", "", "vehicle.chassis.x", 1, 1, 4, 0)
DeclareAlias2("vehicle.y", "", "vehicle.chassis.y", 1, 1, 5, 0)
DeclareVariable("vehicle.ay", "[m/s2]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("vehicle.delta", "[rad]", 0.0, 0.0,0.0,0.0,0,640)
DeclareAlias2("vehicle.vy", "[m/s]", "vehicle.chassis.vy", 1, 1, 0, 0)
DeclareAlias2("vehicle.yaw_velocity", "[s-1]", "vehicle.chassis.yaw_velocity", 1,\
 1, 2, 0)
DeclareAlias2("vehicle.yaw_acc", "[s-2]", "vehicle.chassis.der(yaw_velocity)", 1,\
 6, 2, 0)
DeclareVariable("pi", "", 3.141592653589793, 0.0,0.0,0.0,0,513)
DeclareVariable("swdamp", "amplitude of the swd manouvre", 1.9198621771937625, \
0.0,0.0,0.0,0,513)
EndNonAlias(0)

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double*time, double* X_, double* XD_, double* U_, double* DP_, int IP_[], Dymola_bool LP_[], double* F_, double* Y_, double* W_, double QZ_[], double duser_[], int iuser_[], void*cuser_[],struct DYNInstanceData*did_) {
static Real initStore[1];
}
StartDataBlock
StartEqBlock
DoRemember_(DYNX(F_,2), 0.0, 0);
DoRemember_(DYNX(W_,47), 0.0, 1);
DoRemember_(DYNX(W_,49), 0.0, 2);
EndEqBlock
EndDataBlock
